name: Example testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule: # Run this workflow on a scheduled manner given the cron expression (This is a second event to trigger the workflow)
    - cron: '*/5 * * * *'

permissions:
  contents: read

env:
  message: "Testing code!"

jobs:
  test-code:
    runs-on: ubuntu-latest # The ubuntu-latest label currently uses the Ubuntu 22.04 runner image
    
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checking out our code
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
        
        with:
          python-version: '3.10.14'
          cache: 'pip'
          
      - name: install python packages
        run: |
          python3.10 -m pip install --upgrade pip 
          pip3.10 install -r requirements.txt 
        
      - name: Run your app
        run: python3.10 src/app.py &
      
      - name: Export variables
        run: | 
          echo $PWD
          export ZENML_CONFIG_PATH=$PWD/services/zenml
          export PROJECT_DIR=$PWD >> $GITHUB_ENV
          export AIRFLOW_HOME=$PWD/services/airflow
          export PYTHONPATH=$PWD/src

      - name: Run ZenML server  
        run: zenml down && zenml up
        
      - name: Test with pytest
        run: |
          echo "ZENML_CONFIG_PATH=${{ env.ZENML_CONFIG_PATH }}"
          echo "PROJECT_DIR=${{ env.PROJECT_DIR }}"
          echo "AIRFLOW_HOME=${{ env.AIRFLOW_HOME }}"
          echo "PYTHONPATH=${{ env.PYTHONPATH }}"
          pytest tests
      
  print_info:
    runs-on: ubuntu-latest
    needs: test-code
      
    steps:
      - name: print my password
        run: | 
          echo My password is ${{ secrets.PASSWORD }}
          echo My name is '${{ vars.NAME }}'

      - name: print message
        run: echo $message
